config/routes.rb
SabatonWeb::Application.routes.draw do
    resources :users, except: [:show]
    resources :sessions, only: [:new, :create, :destroy]
    resources :aspect_topics, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]

    root 'static_pages#home'
    get '/static_pages/about', to: 'static_pages#about', as: 'about'
    get '/static_pages/forum', to: 'static_pages#forum', as: 'forum'
    
    match '/signup', to: 'users#new', via: 'get'

    match '/signin', to: 'sessions#new', via: 'get'
    match '/signout', to: 'sessions#destroy', via: 'delete'
    

end

app/models/aspect_topic.rb
class AspectTopic < ActiveRecord::Base
    has_many :comments, dependent: :destroy
    
    belongs_to :user
    default_scope -> {order('created_at DESC')}
    validates :user_id, presence: true
    validates :content, presence: true, length: {maximum: 250}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :user
    belongs_to :aspect_topic
    
    default_scope -> {order('created_at ASC')}
    
    validates :user_id, presence: true
    validates :aspect_topic_id, presence: true
    validates :content, presence: true, length: {maximum: 250}
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :aspect_topics, dependent: :destroy
    has_many :comments, dependent: :destroy
    
    before_save do
        self.email = email.downcase
    end

    before_create :create_remember_token
    
    # All validations happen before objects are saved into db.
    validates :name, presence: true, length: {maximum: 50}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                      uniqueness: {case_sensitive: false}

    validates :password, length: {minimum: 6}
    
    has_secure_password

    def User.new_remember_token
        SecureRandom.urlsafe_base64
    end

    def User.encrypt(token)
        Digest::SHA1.hexdigest(token.to_s)
    end

    private

        def create_remember_token
           self.remember_token = User.encrypt(User.new_remember_token)
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception
    include SessionsHelper
end

app/controllers/aspect_topics_controller.rb
class AspectTopicsController < ApplicationController
    before_action :signed_in_user, only: [:create, :destroy]
    before_action :correct_user, only: [:destroy]
    
    def create
        @topic = current_user.aspect_topics.build(aspect_topic_params)
        if @topic.save
            flash[:success] = "A new topic has been created!"
            redirect_to forum_path
        else
            render 'static_pages/forum'
        end
    end
    
    def destroy
        @topic.destroy
        redirect_to forum_path
    end
    
    private
        def aspect_topic_params
            params.require(:aspect_topic).permit(:content)
        end
        
        def correct_user
            @topic = current_user.aspect_topics.find_by(id: params[:id])
            redirect_to root_url if @topic.nil?
        end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :signed_in_user, only: [:create, :destroy]
    def create
        @comment = current_user.comments.build(comment_params)

        respond_to do |format|
            if @comment.save
                format.js {render json: [{
                                 'aspect_topic_id' => @comment.aspect_topic_id,
                                            'html' => render_to_string(:action => "create", :layout => false)
                                        }]
                }
            else
            end
        end
    end

    def destroy
    end

    private

    def comment_params
        params.require(:comment).permit(:content, :aspect_topic_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            flash[:success] = "You have successfully signed in!"
            # Sign the user in and redirect to the user's show page.
            sign_in user
            redirect_back_or root_url
        else
            # Create an error message and re-render the signin form.
            flash.now[:error] = 'Invalid email/password combination'
            render 'new'
        end
    end

    def destroy
        sign_out
        redirect_to root_url  
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end
    
    def about
    end
    
    def forum
        @current_user = current_user
        @topic = @current_user.aspect_topics.build() if signed_in?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :signed_in_user, only: [:edit, :update]
    before_action :correct_user,   only: [:edit, :update]
    
    def new
        @user = User.new
    end
    
    # def show
        # @user = User.find(params[:id])
        # @topics = @user.aspect_topics.paginate(page: params[:page], per_page: 10)        
    # end
    
    def create
        @user = User.new(user_params)    # Not the final implementation!
        if @user.save
            sign_in @user
            flash[:success] = "Welcome to the Sabaton Studio"
            redirect_to root_url
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        if @user.update_attributes(user_params)
            flash[:success] = "Profile updated";
            sign_in @user
            redirect_to root_url
        else
            render 'edit'
        end
    end
    
    # Use strong parameters to prevent mass assignment vulnerability.
    private
        def user_params
            params.require(:user).permit(:name, :email, :password,
                                         :password_confirmation)
        end
        
        def correct_user
            @user = User.find(params[:id])
            redirect_to root_url, notice: "You are wrong user to access this protected page!!! So naughty!!!" unless current_user?(@user)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title)
        base_title = "Sabaton Games";
        if page_title.empty?
            base_title
        else
            "#{base_title} | #{page_title}"
        end  
    end
    
    def get_logger
        ActiveSupport::TaggedLogging.new(Logger.new(STDOUT))
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
    
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def sign_in(user)
        # Create a new token and add it into the response.
        remember_token = User.new_remember_token
        cookies.permanent[:remember_token] = remember_token
        # Persist the encrypted token into the db.
        user.update_attribute(:remember_token, User.encrypt(remember_token))
        # The page knows who is the current user now.
        current_user = user
    end

    def signed_in?
        !current_user.nil?
    end
    
    def signed_in_user
        unless signed_in?
            store_location
            redirect_to signin_url, notice: "Please sign in!!! Do not be naughty!!!"
        end
    end

    def current_user=(user)
        @current_user = user
    end

    def current_user?(user)
        user == current_user
    end

    # Verify whether user signed in.
    def current_user
        remember_token = User.encrypt(cookies[:remember_token])
        @current_user ||= User.find_by(remember_token: remember_token)
    end

    def sign_out
        self.current_user = nil
        cookies.delete :remember_token
    end

    def redirect_back_or(default)
        # redirect_to(session[:return_to] || default)
        redirect_to root_url
        session.delete(:return_to)
    end

    def store_location
        session[:return_to] = request.url
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    # Returns the Gravatar (http://gravatar.com/) for the given user.
    def gravatar_for(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name)
    end
end

app/views/aspect_topics/_aspect_topic.html.erb
<li id="<%= aspect_topic.id %>" class="row">
    <div class="span7">
        <div class="row">
            <span class="span7"><h4><strong><%= aspect_topic.user.name %></strong></h4></span>
        </div>
        <p></p>
        <div class="row">
            <div class="span1 gravatar">
                <a><%= gravatar_for(aspect_topic.user) %></a>
            </div>
            <span class="content span6"><%= aspect_topic.content %></span>
        </div>
        <div class="row">
            <div class="span7">
                <p></p>
                <p>
                    <i class="icon-time"></i>
                    <span>Created <%= time_ago_in_words(aspect_topic.created_at) %> ago.</span>
                    | <i class="icon-comment"></i>
                    <span class='comment-no'><%= pluralize(aspect_topic.comments.count, "comment") %></span>
                    <% if current_user?(aspect_topic.user) %>
                    | <i class="icon-trash"></i>
                    <%= link_to "Delete", aspect_topic, method: :delete,
                    data: { confirm: "You sure?" },
                    title: aspect_topic.content %>
                    <% end %>
                </p>
            </div>
        </div>
        <div class="row">
            <div class="span7 comments">
                <!-- Comments -->
                <% aspect_topic.comments.to_a.each do |comment| %>
                    <%= render "comments/comment", comment: comment %>
                <p></p>
                <% end %>
            </div>
        </div>
        <% if signed_in? %>
        <div class="row comment-post-form">
            <div class="span7">
                <%= render "comments/comment_form", topic: aspect_topic %>
            </div>
        </div>
        <% end %>
    </div>
</li>

app/views/comments/_comment.html.erb
<div class="row">
    <div class="span1 small-gravatar" style="margin-right: -15px !important;">
        <a><%= gravatar_for(comment.user, options = {size: 40}) %></a>
    </div>
    <div class="span6">
        <div class="row comment-content">
            <div class="span6">
                <span class="user-name"><%= comment.user.name %> </span><span><%= comment.content %></span>
            </div>
        </div>
        <div class="row">
            <div class="span6">
                <span class="date"><%= time_ago_in_words(comment.created_at) %> ago</span>
            </div>
        </div>
    </div>
</div>

app/views/comments/_comment_form.html.erb
<%= form_for current_user.comments.build, :url => {:controller => 'comments', :action => 'create'}, remote: true do |form| %>
<div class="row">
    <div class="span7">
        <%= form.hidden_field :aspect_topic_id, value: topic.id, id: "comment_aspect_topic_id_#{topic.id}" %>
    </div>
</div>
<div class="row">
    <div class="span7">
        <p></p>
        <%= form.text_area :content, placeholder: "Your comment...", id: "comment_content_aspect_topic_id_#{topic.id}" %>
    </div>
</div>
<% end %>

app/views/comments/create.html.erb
<%= render "comments/comment", comment: @comment %>

app/views/layouts/_banner.html.erb
<div id="myCarousel" class="carousel slide">
    <div class="carousel-inner">
        <div class="item active">
            <%= image_tag("banners/banner.jpg", alt: "") %>
            <div class="container">
                <div class="carousel-caption">
                    <h1>Aspects - Multiplayer tower war game</h1>
                    <div class="lead">
                        <ul>
                            <li>Over 19 unique single-player levels</li>
                            <li>16 unique Totems to defend your land</li>
                            <li>12 unique Phantoms to destroy enemies</li>
                            <li>Fight a friend over Wifi or Bluetooth</li>
                        </ul>
                    </div>
                    <!-- <a class="btn btn-large btn-primary" href="#">Browse gallery</a> -->
                </div>
            </div>
        </div>
    </div>
    <!-- <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a> -->
</div>
<div class="container">
    <div id="marketing-btns">
        <span class="marketing-btn"><%= image_tag("apple_store_btn.png", alt: "Apple Store button") %></span>
        <span class="marketing-btn"><%= link_to image_tag("fb_btn.png", alt: "Facebook button"), "https://www.facebook.com/sabatongames", target: "_blank" %></span>
        <span class="marketing-btn"><%= link_to image_tag("twitter_btn.jpg", alt: "Twitter button"), "https://twitter.com/sabatongames", target: "_blank" %></span>
    </div>
</div>

app/views/layouts/_flash.html.erb
<div class="center">
    <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
</div>

app/views/layouts/_header.html.erb
<div class="navbar-wrapper">
    <!-- Wrap the .navbar in .container to center it within the absolutely positioned parent. -->
    <div class="container">
        <div id="logo">
            <%= link_to image_tag("logo.png", alt: "Sabaton Games Studio"), root_path %>
        </div>
        <div class="navbar navbar-inverse">
            <div class="navbar-inner" style="float: right;">
                <!-- Responsive Navbar Part 1: Button for triggering responsive navbar (not covered in tutorial). Include responsive CSS to utilize. -->
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- Responsive Navbar Part 2: Place all navbar contents you want collapsed withing .navbar-collapse.collapse. -->
                <div class="nav-collapse collapse" style="float: right">
                    <ul class="nav">
                        <li id="home-btn" class="<%= 'active' if current_page?(root_path) %>">
                            <%= link_to "Home", root_path %>
                        </li>
                        <li id="forum-btn" class="<%= 'active' if current_page?(forum_path) %>">
                            <%= link_to "Forum", forum_path %>
                        </li>
                        <!-- Read about Bootstrap dropdowns at http://twbs.github.com/bootstrap/javascript.html#dropdowns -->
                        <% if signed_in? %>
                        <li id="account-btn" class="dropdown <%= 'active' if current_page?(edit_user_path current_user) %>">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <%= link_to "Settings", edit_user_path(current_user) %>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <%= link_to "Sign out", signout_path, method: "delete" %>
                                </li>
                            </ul>
                        </li>
                        <% else %>
                        <li id="sign-up-btn" class="<%= 'active' if current_page?(signup_path) %>">
                            <%= link_to "Sign Up", signup_path %>
                        </li>
                        <li id="sign-in-btn" class="<%= 'active' if current_page?(signin_path) %>">
                            <%= link_to "Sign In", signin_path %>
                        </li>
                        <% end %>
                    </ul>
                </div><!--/.nav-collapse -->
            </div><!-- /.navbar-inner -->
        </div><!-- /.navbar -->
    </div>
    <!-- /.container -->
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_social_icons.html.erb
<div id="social-icons">
    <%= link_to image_tag("facebook_button.png", alt: "Facebook"), '#' %>
    <%= link_to image_tag("youtube_button.png", alt: "Youtube"), '#' %>
    <%= link_to image_tag("forum_button.png", alt: "Our forum"), '#' %>
</div>

app/views/layouts/_user_form_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirm Password" %>
<%= f.password_field :password_confirmation %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= full_title(yield(:title)) %></title>
        <%= stylesheet_link_tag "application", media: "all",
        "data-turbolinks-track" => true %>
        <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet">
        <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
        <%= csrf_meta_tags %>
        <%= render 'layouts/shim' %>
    </head>
    <body>
        <%= render 'layouts/header' %>
        <%= render 'layouts/banner' %>
        <div id="main-content" class="container">
            <div class="row">
                <div class="span12">
                    <%= render 'layouts/flash' %>
                    <%= yield %>
                </div>
            </div>
        </div>
        <!-- <%= debug(params) if Rails.env.development? %> -->
    </body>
</html>

app/views/layouts/social_icons.html.erb
<div id="social-icons">
    <%= link_to image_tag("facebook_button.png", alt: "Facebook"), '#' %>
    <%= link_to image_tag("youtube_button.png", alt: "Youtube"), '#' %>
    <%= link_to "Our forum", '#', class: "btn btn-large btn-primary" %>
</div>

app/views/shared/_create_topic_form.html.erb
<div class="row">
    <div class="span4">
        <%= form_for @topic, :url => {:controller => 'aspect_topics', :action => 'create'} do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="field row">
            <div class="span4"><%= f.text_area :content, placeholder: "Create new topic..." %></div>
        </div>
        <div class="field row">
            <div class="span4"><%= f.submit "Create", class: "btn btn-primary" %></div>
        </div>
        <% end %>
    </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
    <div class="alert alert-error">
        The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
        <% object.errors.full_messages.each do |msg| %>
        <li>
            * <%= msg %>
        </li>
        <% end %>
    </ul>
</div>
<% end %>

app/views/shared/_user_info.html.erb
<div class="row">
    <div class="span4" id="current-user">
        <div class="row">
            <span class="span4"><h4><strong><%= user.name %></strong></h4></span>
        </div>
        <p></p>
        <div class="row">
            <div class="span1 gravatar">
                <a><%= gravatar_for user %></a>
            </div>
            <span class="content span2">
                <div>
                    <i><%= user.email %></i>
                </div>
                <div>
                    Created <%= pluralize(user.aspect_topics.count, "topic") %>
                </div> 
            </span>
        </div>
    </div>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %> 
<h1>About Us</h1>
<h2>
    Here are information about our studio!!!
</h2>

app/views/static_pages/forum.html.erb
<% provide(:title, 'Aspects Forum') %> <h1>Aspects Forum</h1>
<div class="row">
    <aside class="span4">
    <% if signed_in? %>
        <%= render 'shared/user_info', user: @current_user %>
        <hr>
        <%= render 'shared/create_topic_form' %>
    <% end %>
    </aside>
    <div class="span1"></div>
    <div class="span7">
        <% topics = @topics = AspectTopic.all.paginate(page: params[:page], per_page: 10)
        if topics.any? %>
        <div class="row">
            <div class="span7">
                <h3>No. of topics: <%= topics.count %></h3>
            </div>
        </div>
        <ol class="topics row">
            <%= render topics %>
        </ol>
        <%= will_paginate topics %>
        <% end %>
    </div>
</div>

app/views/static_pages/home.html.erb
<hr />
<div class="featurette">
    <%= image_tag("aspects_logo.png", alt: "Aspects logo", class: "flex-img") %>
    <%= image_tag("arts/avatar_galen_ally.png", class: "pull-right featurette-image") %>
    <div class="lead">
        <p>
            <b>Aspects</b> is the first ever inter-device multiplayer tower war game to be introduced to the mobile platform. Players do not only defend against waves of enemies, but also send forces to defeat their opponents.
        </p>
        <p>
            <b>Release Date:</b> Aspects will be available on the Apple App Store end of 2013.
        </p>
        <p>
            <b>Platform:</b> iOS devices, iOS 5 and above
        </p>
    </div>
</div>
<hr />
<div class="row">
    <div class="span12">
        <div class="flex-video">
            <iframe class="video" src="http://www.youtube.com/embed/ge0oR8AZ3Qw" frameborder="0" allowfullscreen="">
                <html lang="en" dir="ltr">
            </iframe>
        </div>
    </div>
</div>
<hr />
<div class="featurette">
    <%= image_tag("arts/titans.jpg", class: "pull-left flex-img") %>
    <div class="flex-gap"></div>
    <div class="lead">
        <p>
            <b>Sabaton Games</b> is a mobile games company that is founded by a small team of programmers and game artists who first met in summer 2012 during the Singapore-MIT GAMBIT Game Lab internship program in Cambridge. The games we had worked on with our individual teams in the program have achieved a good degree of recognition – one has been included in online articles in leading game-focused sites Gamasutra and Kotaku; another game has made one of the finalists for 2013 IndieCade, an international juried festival of independent games.
        </p>
        <p>
            We are a team of game developers with the shared passion of bringing depth to mobile gaming.
        </p>
    </div>
</div>
<hr />
<div class="hero-unit white-panel">
    <h2 class="featurette-heading">Concept Art</h2>
    <p>
        Character and environment designs are largely influenced by tribal motifs and native superstitions from around the world. The concept is also reflected in the music and sound effects in the game, which were composed by Hexany Audio.
    </p>
    <p>
        Players can choose to play as any one of the 3 main characters: <b>Vulc, Ullr & Gea.</b>
    </p>
</div>
<div class="row avatars">
    <div class="span4 card">
        <%= image_tag("arts/avatar_vulc.jpg") %>
    </div>
    <div class="span4 card">
        <%= image_tag("arts/avatar_ullr.jpg") %>
    </div>
    <div class="span4 card">
        <%= image_tag("arts/avatar_gea.jpg") %>
    </div>
</div>
<div class="flex-mini-gap"></div>
<hr />
<div class="hero-unit white-panel">
    <p>
        Final painted renderings of some secondary characters that players will encounter during game play.
    </p>
</div>
<div class="row concept_arts">
    <!-- <div class="span12">
    <div class="row">
    <div class="span6">
    <%= image_tag("arts/concept_the_messenger.jpg") %>
    </div>
    <div class="span6">
    <%= image_tag("arts/concept_golem.jpg") %>
    </div>
    </div>
    </div> -->
    <div class="span12">
        <div class="row">
            <div class="span6">
                <%= image_tag("arts/concept_elrina.jpg") %>
            </div>
            <div class="span6">
                <%= image_tag("arts/avatar_miniboss.png") %>
            </div>
        </div>
    </div>
    <div class="span12">
        <div class="row">
            <div class="span6">
                <%= image_tag("arts/avatar_008.png") %>
            </div>
            <div class="span6">
                <%= image_tag("arts/avatar_009.png") %>
            </div>
        </div>
    </div>
    <div class="span12">
        <div class="row">
            <div class="span6">
                <%= image_tag("arts/avatar_010.png") %>
            </div>
            <div class="span6">
                <%= image_tag("arts/avatar_soldier.png") %>
            </div>
        </div>
    </div>
</div>
<div class="flex-mini-gap"></div>
<hr />
<div class="hero-unit white-panel">
    <p>
        A draft of some of the primary Totems before the production of sprite sheets.
    </p>
</div>
<div class="row">
    <div class="span12">
        <%= image_tag("towers.jpg") %>
    </div>
</div>
<div class="flex-mini-gap"></div>
<hr />
<div class="hero-unit white-panel">
    <p>
        Final map designs that are included in the game.
    </p>
</div>
<div class="row maps">
    <div class="span3">
        <%= image_tag("maps/map1.jpg") %>
    </div>
    <div class="span3">
        <%= image_tag("maps/map2.jpg") %>
    </div>
    <div class="span3">
        <%= image_tag("maps/map3.jpg") %>
    </div>
    <div class="span3">
        <%= image_tag("maps/map4.jpg") %>
    </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit User")%> <h1>Update Profile</h1>
<div class="row">
    <div class="span6 offset3">
        <div class=" white-panel">
            <%= form_for(@user) do |f| %>
            <%= render 'layouts/user_form_fields', f: f %>
            <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
            <% end %>
            <%= gravatar_for @user %>
            <a href="http://gravatar.com/emails">Change</a>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %> <h1>Sign Up</h1>
<div class="row">
    <div class="span6 offset3">
        <div class=" white-panel">
            <%= form_for(@user) do |f| %>
            <%= render 'layouts/user_form_fields', f: f %>
            <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
            <% end %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="block8 centralized">
    <aside class="span5">
        <%= render 'shared/user_info', user: @user %>
    </aside>
    <div class="span7">
        <% if @user.aspect_topics.any? %>
        <h3>No. of topics: <%= @user.aspect_topics.count %></h3>
        <ol class="topics">
            <%= render @topics %>
        </ol>
        <%= will_paginate @topics %>
        <% end %>
    </div>
</div>